### ISSUE TITLE
more info

### ISSUE THREAD

**Issue by le0m** [josdemmers/Grepolis2Bot#2]
Hello, i really didn't know how to contact you on GitHub, so i'm opening an issue.

I'm building a bot for another browsergame and i'm studing yours to get ideas on how to do some things, but i'm proceding slowly since it's a quite big project and it's using patterns i don't know.
Could you explain in details how the building queue (and timer) works?

**Comment by tpauwels** [comment]
Hello,
I'm afraid I can't help you since I'm not the owner of this project. The owner & designer of the bot is https://github.com/josdemmers. He made it opensource so feel free to use the logics & parts of the code. If you have specific questions about the bot I suggest you contact the designer.

**Comment by josdemmers** [comment]
No problem, this works as well. Could post a similar message at the link below with your email address so I can contact you (email is only visible for me). That makes it easier to communicate.
http://bots.uthar.nl/35/mybot-tutorial-part-1

Or you could just post your email address here if you don't mind making it public.

**Comment by le0m** [comment]
I did, thanks for the reply
